Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
pg_engine = create_engine(postgres_conn_str)
mysql_engine = create_engine(mysql_conn_str)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[7], line 1[0m
[0;32m----> 1[0m pg_engine [38;5;241m=[39m [43mcreate_engine[49m[43m([49m[43mpostgres_conn_str[49m[43m)[49m
[1;32m      2[0m mysql_engine [38;5;241m=[39m create_engine(mysql_conn_str)

File [0;32m<string>:2[0m, in [0;36mcreate_engine[0;34m(url, **kwargs)[0m

File [0;32m/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py:281[0m, in [0;36mdeprecated_params.<locals>.decorate.<locals>.warned[0;34m(fn, *args, **kwargs)[0m
[1;32m    274[0m     [38;5;28;01mif[39;00m m [38;5;129;01min[39;00m kwargs:
[1;32m    275[0m         _warn_with_version(
[1;32m    276[0m             messages[m],
[1;32m    277[0m             versions[m],
[1;32m    278[0m             version_warnings[m],
[1;32m    279[0m             stacklevel[38;5;241m=[39m[38;5;241m3[39m,
[1;32m    280[0m         )
[0;32m--> 281[0m [38;5;28;01mreturn[39;00m [43mfn[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/sqlalchemy/engine/create.py:549[0m, in [0;36mcreate_engine[0;34m(url, **kwargs)[0m
[1;32m    546[0m kwargs[38;5;241m.[39mpop([38;5;124m"[39m[38;5;124mempty_in_strategy[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m)
[1;32m    548[0m [38;5;66;03m# create url.URL object[39;00m
[0;32m--> 549[0m u [38;5;241m=[39m [43m_url[49m[38;5;241;43m.[39;49m[43mmake_url[49m[43m([49m[43murl[49m[43m)[49m
[1;32m    551[0m u, plugins, kwargs [38;5;241m=[39m u[38;5;241m.[39m_instantiate_plugins(kwargs)
[1;32m    553[0m entrypoint [38;5;241m=[39m u[38;5;241m.[39m_get_entrypoint()

File [0;32m/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/sqlalchemy/engine/url.py:856[0m, in [0;36mmake_url[0;34m(name_or_url)[0m
[1;32m    840[0m [38;5;250m[39m[38;5;124;03m"""Given a string, produce a new URL instance.[39;00m
[1;32m    841[0m 
[1;32m    842[0m [38;5;124;03mThe format of the URL generally follows `RFC-1738[39;00m
[0;32m   (...)[0m
[1;32m    852[0m 
[1;32m    853[0m [38;5;124;03m"""[39;00m
[1;32m    855[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(name_or_url, [38;5;28mstr[39m):
[0;32m--> 856[0m     [38;5;28;01mreturn[39;00m [43m_parse_url[49m[43m([49m[43mname_or_url[49m[43m)[49m
[1;32m    857[0m [38;5;28;01melif[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(name_or_url, URL) [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m [38;5;28mhasattr[39m(
[1;32m    858[0m     name_or_url, [38;5;124m"[39m[38;5;124m_sqla_is_testing_if_this_is_a_mock_object[39m[38;5;124m"[39m
[1;32m    859[0m ):
[1;32m    860[0m     [38;5;28;01mraise[39;00m exc[38;5;241m.[39mArgumentError(
[1;32m    861[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mExpected string or URL object, got [39m[38;5;132;01m{[39;00mname_or_url[38;5;132;01m!r}[39;00m[38;5;124m"[39m
[1;32m    862[0m     )

File [0;32m/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/sqlalchemy/engine/url.py:917[0m, in [0;36m_parse_url[0;34m(name)[0m
[1;32m    914[0m     name [38;5;241m=[39m components[38;5;241m.[39mpop([38;5;124m"[39m[38;5;124mname[39m[38;5;124m"[39m)
[1;32m    916[0m     [38;5;28;01mif[39;00m components[[38;5;124m"[39m[38;5;124mport[39m[38;5;124m"[39m]:
[0;32m--> 917[0m         components[[38;5;124m"[39m[38;5;124mport[39m[38;5;124m"[39m] [38;5;241m=[39m [38;5;28;43mint[39;49m[43m([49m[43mcomponents[49m[43m[[49m[38;5;124;43m"[39;49m[38;5;124;43mport[39;49m[38;5;124;43m"[39;49m[43m][49m[43m)[49m
[1;32m    919[0m     [38;5;28;01mreturn[39;00m URL[38;5;241m.[39mcreate(name, [38;5;241m*[39m[38;5;241m*[39mcomponents)  [38;5;66;03m# type: ignore[39;00m
[1;32m    921[0m [38;5;28;01melse[39;00m:

[0;31mValueError[0m: invalid literal for int() with base 10: 'None'

